### ISSUE TITLE
Route Model Implementation

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder-android#10]
Current progress of the route object
- [x] Able to read fields
- [x] Able to set fields

**Comment by aj-michael** [comment]
I don't think it makes sense for the user to set fields on routes.

**Comment by robinsdm** [comment]
The user isn't setting fields. I was thinking they should be immutable objects. Since they shouldn't be changed after created. You should just be able to create and get fields.

**Comment by aj-michael** [comment]
:+1: for immutability. I was referring to the fact that you made a checkbox for "Able to set fields", does that mean something else?

**Comment by robinsdm** [comment]
No it should just be a constructor.

**Comment by robinsdm** [comment]
This is done.
