### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder-android#27]
- [x] authentication method that triggers authentication process
- [x] ability execute code once authentication finishes, this can be done through passing a callback to the authentication method or by adding an onAuthentication function
- [x] connect provides connection id used for authentication

**Comment by danhanson** [comment]
Moved to sprint 12

**Comment by robinsdm** [comment]
This should be complete in the latest pull request #37.

**Comment by aj-michael** [comment]
:rocket:
