### ISSUE TITLE
Add ChimneySwap demo app to repo

### ISSUE THREAD

**Issue by robinsdm** [CSSE497/pathfinder-android#29]
- [x] Need to remove API Keys
- [x] Move the project to GitHub

**Comment by aj-michael** [comment]
Where is it right now..?

**Comment by robinsdm** [comment]
Currently it is only on my hard disk.

**Comment by robinsdm** [comment]
I didn't what to put it into version control until I clean up and remove all the API keys for Google Services.

**Comment by aj-michael** [comment]
Oh... We really should have had that in version control many weeks ago

**Comment by robinsdm** [comment]
Completed
